name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: 'Install Firebase CLI'
        run: npm install -g firebase-tools

      - name: 'Deploy to Firebase Hosting'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          firebase deploy --only hosting --project lock-recon -m "Direct Auth Deploy"
